sonar.projectKey=pixime-net_talk-ui
sonar.organization=pixime-net

sonar.sources=src
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test-setup.ts,src/routeTree.gen.ts

sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
